### ISSUE TITLE
Custom file name String.Format issue

### ISSUE THREAD

**Issue by Naggischnulu** [andi0b/journey-markdown-converter#3]
I'm trying to use the custom file name option, however when using String.Format to format the date (like in the default `{{String.Format date_journal "yyyy-MM-dd"}}`) I get the error `System.ArgumentException: Object of type 'HandlebarsDotNet.UndefinedBindingResult' cannot be converted to type 'System.String'.` I'm not that experienced in code and probably I'm just making some mistake, but I couldn't solve the problem so far.

**Comment by andi0b** [comment]
Sorry for the late reply, I thikg you have an issue with escaping the argument in your shell.

For me using Powershell this syntax works:
```powershell
.\journey-markdown-converter.exe  -n '{{String.Format date_journal "yyyy-MM-dd"}}' .\journey-multiple-1.zip
```

I tried it with bash on Linux too, works the same way:
```bash
./journey-markdown-converter -n '{{String.Format date_journal "yyyy-MM-dd"}}' journey-multiple-1.zip
```

If this solution doesn't work, please let me know and I'll reopen this issue.
