### ISSUE TITLE
Required argument missing for command: journey-markdown-converter

### ISSUE THREAD

**Issue by Unvented9039** [andi0b/journey-markdown-converter#4]
Hello! Hoping against hope that you're still checking in on this project because I saw where you mentioned that you weren't developing this anymore.

Anyway, I downloaded the Windows binary and when I run it on Windows 11, I get this error: Required argument missing for command: journey-markdown-converter

The window actually only opens briefly and then closes.

So, if there's any help you can offer, that would be amazing.

**Comment by andi0b** [comment]
Are you using the program in the terminal as a CLI command? There is no UI, just double clicking won’t do anything, and just pop up a console window briefly. 

Can you please share the full command line you are using it with? Something like: 

```
$ journey-markdown-converter —arg1 value infile.zip

Some output printed to the console..
```

**Comment by Unvented9039** [comment]
I didn't even realize it had to be run in the terminal. I'm not very well versed in doing that. 

I'm thinking Chat GPT can help me here with a good command line. Thanks for the help so far, and I hope it's okay if I come back with any further questions.

**Comment by andi0b** [comment]
Great idea, just post the README into Chat GPT and it should be able to make some suggestions.

But the command for converting one export is only `journey-markdown-converter export.zip`, without any more arguments.

I haven't tested it for a while though, maybe the export format changed.
